name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Juice Shop Docker image
        run: docker pull bkimminich/juice-shop

      - name: Run Juice Shop container
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
