name: Talisman Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  talisman_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Talisman
      - name: Install Talisman
        run: |
          curl -fsSL https://thoughtworks.github.io/talisman/install.sh | bash
          echo "Talisman installed successfully"

      # Étape 3 : Vérifier que Talisman est bien installé
      - name: Verify Talisman installation
        run: talisman --version

      # Étape 4 : Exécuter un scan Talisman sur tous les fichiers suivis par Git
      - name: Run Talisman scan
        run: talisman --scan
        continue-on-error: true

      # Étape 5 : Générer un rapport HTML si des erreurs sont détectées
      - name: Generate HTML report
        if: failure()
        run: |
          mkdir -p reports
          talisman --scanWithHtml > reports/talisman-report.html
          echo "HTML report generated: reports/talisman-report.html"

      # Étape 6 : Télécharger le rapport HTML comme artefact GitHub
      - name: Upload Talisman report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: talisman-report
          path: reports/talisman-report.html
